### ISSUE TITLE
Custom queries - Start loading articles from number xx

### ISSUE THREAD

**Issue by philmarty** [joolanders/ytp-source-k2#6]
When using a multiple element in the builder with custom query, it would be useful to be able to load article from a specific number.

For example: https://nimb.ws/zY1U9S
We use several multiple elements to load article from news categories.
The first element, slideshow, loads the first 3 articles.
The second element, list, loads 5 more items. We need to load the items from the fourth one onwards, so that the first three items are not duplicated.
Backend link: https://zooffs.a51.fr/administrator/index.php?option=com_ajax&templateStyle=12&p=customizer&format=html&site=https%3A%2F%2Fzooffs.a51.fr%2Findex.php

**Comment by miljan-aleksic** [comment]
Hi Phil,

this should be possible now, I have added a custom helper for loading the items. Can you please test it?

**Comment by philmarty** [comment]
Hello Miljan,

Thanks a lot for that new feature :)
I'm off today but I was eager to test so I updated your extension files.
It works like a charm! I can choose the beginner item for a multiple
element.
Thanks again :)

I see that another person has difficulties using K2 as content source, it's
curious as it seems so easy by my side :)
I hope you can fix that quickly.

Cheers
Phil
