### ISSUE TITLE
Sort K2 tags for easy filtering

### ISSUE THREAD

**Issue by philmarty** [joolanders/ytp-source-k2#9]
Hello,

When selecting k2 items by tags, all tags are listed as created: unordered ^^
Would it be possible to display them in alphabetical order?
https://nimb.ws/PnSfxa
Moreover, the number of tags displayed depends on the quantity chosen for the display of the lists in K2 :) Would it be possible to display ALL the tags in the Yootheme element, even if we decide to display only 50 lines at a time in the K2 admin?

**Comment by miljan-aleksic** [comment]
Hi Phil! Let me know if the fix worked it out.
